### ISSUE TITLE
没有独立显卡能用吗？

### ISSUE THREAD

**Issue by kiwiw** [Yshanchui/Hackintosh-12600K-MAXSUN-B660M-MS-TERMINATOR#5]
只有单cpu 12400，没有显卡，可以用吗，谢谢。

**Comment by Yshanchui** [comment]
可以装上系统，最初我也没有独显的时候，安装的。会有个32m的模拟显卡显示图形。但是不推荐这样做，应该显存问题，导致响应慢且浏览器无法渲然。
