### ISSUE TITLE
可以使用ax201 蓝牙吗？

### ISSUE THREAD

**Issue by liufeng5120** [Yshanchui/Hackintosh-12600K-MAXSUN-B660M-MS-TERMINATOR#6]
启用了intel wifi 蓝牙 kext文件，ax201 wifi能用蓝牙无法驱动。B660M终结者不是只有一个前置usb9针插口吗？你的BCM94360CD的怎么接的。

**Comment by Yshanchui** [comment]
BlueToolFixup、IntelBluetoothFirmware、BrcmFirmwareData需要都勾选开启。 ax201早期我使用是可以正常使用的。
BCM94360CD直接占有了前置usb9针插口。
